name: P1
on:
  push:
    branches: 
       - main
permissions: # this is to give the write permisson so that the files can be created 
   contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Git user
          run: |
            git config --global user.name "${{ github.actor }}"  # Using the GitHub actor
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"  # Use the noreply email address
        - name: Create file "f1.txt"
          run: |
             echo "Hi...I am file 1" > f1.txt
             git add f1.txt
             git commit -m "Add f1 file"
             git push origin main
        - name: Create a new file in a specific branch
          run: |
            # Create a new branch
            git checkout -b feature-branch
            # Create a new file in a specific branch: - 
            echo "Hello World" > f2.txt
            git add f2.txt

            
            # Commit the changes
            git commit -m "Add file f2 to feature-branch"
            
            # Push the changes to 'feature-branch'
            git push origin feature-branch